{
  "name": "your-project-name",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "webpack --mode production", // ตัวอย่างคำสั่ง build
    "start": "webpack-dev-server --mode development" // ตัวอย่างคำสั่ง start development server
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    // "bootstrap": "^4.6.2", // ตัวอย่าง dependency
    // "jquery": "^3.6.3" // ตัวอย่าง dependency
  },
  "devDependencies": {
    "webpack": "^5.80.0", // ตัวอย่าง dependency
    "webpack-cli": "^5.0.1", // ตัวอย่าง dependency
    "webpack-dev-server": "^4.12.0" // ตัวอย่าง dependency
  }
}
